### ISSUE TITLE
Constructor returns before HTTP listener is initialized

### ISSUE THREAD

**Issue by zadam** [jrharmon/MockHttpServer#5]
Problem is in the MockServer class constructor - it calls HandleRequests(int port) which is an async method, but without await - so it returns immediately - before this._listener.Start() call is finished.

Solution would be that this HttpListener is initialized outside of this async method so constructor waits for it to finish before returning.

Problem scenario:
1. Construct instance of MockServer with all the parameters
2. Execute request to the mock server
3. Request fails because HttpListener is not started at this point yet

**Comment by jrharmon** [comment]
Thanks for the feedback.  I have never seen the listener not activate before the first time I called it, but moved the _listener creation and initialization out of the HandleRequests method.
