### ISSUE TITLE
Support changing request handlers on the fly

### ISSUE THREAD

**Issue by zadam** [jrharmon/MockHttpServer#6]
MockServer instance is quite heavy to construct - because of the HttpListener initialization.

Currently, the only way to define the mapping is in the constructor. This means that if we want to use MockServer in our tests - each with their own request handler(s) - we need to create and dispose the MockServer instance for each individual test which is quite expensive.

For this scenario, it would be better to have one shared instance of MockServer for whole test class or even all tests - each test would then simply define its own request handler in the running mock server and then clean up after.

MockServer would then have methods like:

`void AddRequestHandler(MockHttpHandler handler)`
`void RemoveAllRequestHandlers()`

Or something similar.

**Comment by jrharmon** [comment]
The standard method for using this library with multiple tests would be to re-create it for each test, with its own set of handlers.  I never noticed much of a performance hit, as for me, the constructor takes about 128 ms to complete.

I can't remember why I didn't allow updating the handler list, as I remember their being a reason, but I think that was just early on, before using the method in place currently, and I see no reason to not allow updates to it.  The latest commit adds support for this, and an update should be going to Nuget soon.
