### ISSUE TITLE
Admin rights and HttpListener registration

### ISSUE THREAD

**Issue by jakubin** [jrharmon/MockHttpServer#7]
As you noted on readme, the current implementation requires either admin rights or adding the port using netsh.
However, if you allowed non-wildcard registration, i.e. "http://localhost:XYZ" instead of "http://+:XYZ", that would work without admin rights (at least tested on Win10).

**Comment by jrharmon** [comment]
Thanks for the tip.  I was under the impression that you needed to use a wildcard, and didn't realize that you could specify a host name directly.  Localhost is the new default now, and you can specify any host name, isntead of just a single character.
